# ##### BEGIN GPL LICENSE BLOCK #####
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software Foundation,
#  Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# ##### END GPL LICENSE BLOCK #####

from ...constants import Classification

# BEGIN Function Pointers

MODEL_FN_PTR_1_K1_PC = 4273776
MODEL_FN_PTR_1_K2_PC = 4285200
MODEL_FN_PTR_2_K1_PC = 4216096
MODEL_FN_PTR_2_K2_PC = 4216320
MODEL_FN_PTR_1_K1_XBOX = 4254992
MODEL_FN_PTR_2_K1_XBOX = 4255008
MODEL_FN_PTR_1_K2_XBOX = 4285872
MODEL_FN_PTR_2_K2_XBOX = 4216016

ANIM_FN_PTR_1_K1_PC = 4273392
ANIM_FN_PTR_2_K1_PC = 4451552
ANIM_FN_PTR_1_K2_PC = 4284816
ANIM_FN_PTR_2_K2_PC = 4522928
ANIM_FN_PTR_1_K1_XBOX = 4253536
ANIM_FN_PTR_2_K1_XBOX = 4573360
ANIM_FN_PTR_1_K2_XBOX = 4285488
ANIM_FN_PTR_2_K2_XBOX = 4523088

MESH_FN_PTR_1_K1_PC = 4216656
MESH_FN_PTR_2_K1_PC = 4216672
MESH_FN_PTR_1_K2_PC = 4216880
MESH_FN_PTR_2_K2_PC = 4216896
MESH_FN_PTR_1_K1_XBOX = 4267376
MESH_FN_PTR_2_K1_XBOX = 4264048
MESH_FN_PTR_1_K2_XBOX = 4216576
MESH_FN_PTR_2_K2_XBOX = 4216592

SKIN_FN_PTR_1_K1_PC = 4216592
SKIN_FN_PTR_1_K2_PC = 4216816
SKIN_FN_PTR_2_K1_PC = 4216608
SKIN_FN_PTR_2_K2_PC = 4216832
SKIN_FN_PTR_1_K1_XBOX = 4264032
SKIN_FN_PTR_2_K1_XBOX = 4264048
SKIN_FN_PTR_1_K2_XBOX = 4216512
SKIN_FN_PTR_2_K2_XBOX = 4216528

DANGLY_FN_PTR_1_K1_PC = 4216640
DANGLY_FN_PTR_1_K2_PC = 4216864
DANGLY_FN_PTR_2_K1_PC = 4216624
DANGLY_FN_PTR_2_K2_PC = 4216848
DANGLY_FN_PTR_1_K1_XBOX = 4266736
DANGLY_FN_PTR_2_K1_XBOX = 4266720
DANGLY_FN_PTR_1_K2_XBOX = 4216560
DANGLY_FN_PTR_2_K2_XBOX = 4216544

# END Function Pointers

MODEL_MODEL = 2
MODEL_ANIM = 5

CLASS_OTHER = 0x00
CLASS_EFFECT = 0x01
CLASS_TILE = 0x02
CLASS_CHARACTER = 0x04
CLASS_DOOR = 0x08
CLASS_LIGHTSABER = 0x10
CLASS_PLACEABLE = 0x20
CLASS_FLYER = 0x40

CLASS_BY_VALUE = {
    CLASS_OTHER: Classification.OTHER,
    CLASS_EFFECT: Classification.EFFECT,
    CLASS_TILE: Classification.TILE,
    CLASS_CHARACTER: Classification.CHARACTER,
    CLASS_DOOR: Classification.DOOR,
    CLASS_LIGHTSABER: Classification.LIGHTSABER,
    CLASS_PLACEABLE: Classification.PLACEABLE,
    CLASS_FLYER: Classification.FLYER,
}

NODE_BASE = 0x0001
NODE_LIGHT = 0x0002
NODE_EMITTER = 0x0004
NODE_REFERENCE = 0x0010
NODE_MESH = 0x0020
NODE_SKIN = 0x0040
NODE_DANGLY = 0x0100
NODE_AABB = 0x0200
NODE_SABER = 0x0800

MDX_FLAG_VERTEX = 0x0001
MDX_FLAG_UV1 = 0x0002
MDX_FLAG_UV2 = 0x0004
MDX_FLAG_UV3 = 0x0008
MDX_FLAG_UV4 = 0x0010
MDX_FLAG_NORMAL = 0x0020
MDX_FLAG_COLOR = 0x0040
MDX_FLAG_TANGENT1 = 0x0080
MDX_FLAG_TANGENT2 = 0x0100
MDX_FLAG_TANGENT3 = 0x0200
MDX_FLAG_TANGENT4 = 0x0400

EMITTER_FLAG_P2P = 0x0001
EMITTER_FLAG_P2P_SEL = 0x0002
EMITTER_FLAG_AFFECTED_WIND = 0x0004
EMITTER_FLAG_TINTED = 0x0008
EMITTER_FLAG_BOUNCE = 0x0010
EMITTER_FLAG_RANDOM = 0x0020
EMITTER_FLAG_INHERIT = 0x0040
EMITTER_FLAG_INHERIT_VEL = 0x0080
EMITTER_FLAG_INHERIT_LOCAL = 0x0100
EMITTER_FLAG_SPLAT = 0x0200
EMITTER_FLAG_INHERIT_PART = 0x0400
EMITTER_FLAG_DEPTH_TEXTURE = 0x0800
EMITTER_FLAG_13 = 0x1000
EMITTER_FLAG_KNOWN_MASK = (
    EMITTER_FLAG_P2P
    | EMITTER_FLAG_P2P_SEL
    | EMITTER_FLAG_AFFECTED_WIND
    | EMITTER_FLAG_TINTED
    | EMITTER_FLAG_BOUNCE
    | EMITTER_FLAG_RANDOM
    | EMITTER_FLAG_INHERIT
    | EMITTER_FLAG_INHERIT_VEL
    | EMITTER_FLAG_INHERIT_LOCAL
    | EMITTER_FLAG_SPLAT
    | EMITTER_FLAG_INHERIT_PART
    | EMITTER_FLAG_DEPTH_TEXTURE
    | EMITTER_FLAG_13
)

AABB_NO_CHILDREN = 0x00
AABB_POSITIVE_X = 0x01
AABB_POSITIVE_Y = 0x02
AABB_POSITIVE_Z = 0x04
AABB_NEGATIVE_X = 0x08
AABB_NEGATIVE_Y = 0x10
AABB_NEGATIVE_Z = 0x20

NUM_SABER_VERTS = 176
CTRL_FLAG_BEZIER = 0x10

CTRL_BASE_POSITION = 8
CTRL_BASE_ORIENTATION = 20
CTRL_MESH_SCALE = 36
CTRL_MESH_SELFILLUMCOLOR = 100
CTRL_MESH_ALPHA = 132
CTRL_LIGHT_COLOR = 76
CTRL_LIGHT_RADIUS = 88
CTRL_LIGHT_SHADOWRADIUS = 96
CTRL_LIGHT_VERTICALDISPLACEMENT = 100
CTRL_LIGHT_MULTIPLIER = 140
CTRL_EMITTER_ALPHAEND = 80
CTRL_EMITTER_ALPHASTART = 84
CTRL_EMITTER_BIRTHRATE = 88
CTRL_EMITTER_BOUNCE_CO = 92
CTRL_EMITTER_COMBINETIME = 96
CTRL_EMITTER_DRAG = 100
CTRL_EMITTER_FPS = 104
CTRL_EMITTER_FRAMEEND = 108
CTRL_EMITTER_FRAMESTART = 112
CTRL_EMITTER_GRAV = 116
CTRL_EMITTER_LIFEEXP = 120
CTRL_EMITTER_MASS = 124
CTRL_EMITTER_P2P_BEZIER2 = 128
CTRL_EMITTER_P2P_BEZIER3 = 132
CTRL_EMITTER_PARTICLEROT = 136
CTRL_EMITTER_RANDVEL = 140
CTRL_EMITTER_SIZESTART = 144
CTRL_EMITTER_SIZEEND = 148
CTRL_EMITTER_SIZESTART_Y = 152
CTRL_EMITTER_SIZEEND_Y = 156
CTRL_EMITTER_SPREAD = 160
CTRL_EMITTER_THRESHOLD = 164
CTRL_EMITTER_VELOCITY = 168
CTRL_EMITTER_XSIZE = 172
CTRL_EMITTER_YSIZE = 176
CTRL_EMITTER_BLURLENGTH = 180
CTRL_EMITTER_LIGHTNINGDELAY = 184
CTRL_EMITTER_LIGHTNINGRADIUS = 188
CTRL_EMITTER_LIGHTNINGSCALE = 192
CTRL_EMITTER_LIGHTNINGSUBDIV = 196
CTRL_EMITTER_LIGHTNINGZIGZAG = 200
CTRL_EMITTER_ALPHAMID = 216
CTRL_EMITTER_PERCENTSTART = 220
CTRL_EMITTER_PERCENTMID = 224
CTRL_EMITTER_PERCENTEND = 228
CTRL_EMITTER_SIZEMID = 232
CTRL_EMITTER_SIZEMID_Y = 236
CTRL_EMITTER_RANDOMBIRTHRATE = 240
CTRL_EMITTER_TARGETSIZE = 252
CTRL_EMITTER_NUMCONTROLPTS = 256
CTRL_EMITTER_CONTROLPTRADIUS = 260
CTRL_EMITTER_CONTROLPTDELAY = 264
CTRL_EMITTER_TANGENTSPREAD = 268
CTRL_EMITTER_TANGENTLENGTH = 272
CTRL_EMITTER_COLORMID = 284
CTRL_EMITTER_COLOREND = 380
CTRL_EMITTER_COLORSTART = 392
CTRL_EMITTER_DETONATE = 502


EMITTER_CONTROLLER_KEYS = [
    (CTRL_EMITTER_ALPHAEND, "alphaend", 1),
    (CTRL_EMITTER_ALPHASTART, "alphastart", 1),
    (CTRL_EMITTER_BIRTHRATE, "birthrate", 1),
    (CTRL_EMITTER_BOUNCE_CO, "bounce_co", 1),
    (CTRL_EMITTER_COMBINETIME, "combinetime", 1),
    (CTRL_EMITTER_DRAG, "drag", 1),
    (CTRL_EMITTER_FPS, "fps", 1),
    (CTRL_EMITTER_FRAMEEND, "frameend", 1),
    (CTRL_EMITTER_FRAMESTART, "framestart", 1),
    (CTRL_EMITTER_GRAV, "grav", 1),
    (CTRL_EMITTER_LIFEEXP, "lifeexp", 1),
    (CTRL_EMITTER_MASS, "mass", 1),
    (CTRL_EMITTER_P2P_BEZIER2, "p2p_bezier2", 1),
    (CTRL_EMITTER_P2P_BEZIER3, "p2p_bezier3", 1),
    (CTRL_EMITTER_PARTICLEROT, "particlerot", 1),
    (CTRL_EMITTER_RANDVEL, "randvel", 1),
    (CTRL_EMITTER_SIZESTART, "sizestart", 1),
    (CTRL_EMITTER_SIZEEND, "sizeend", 1),
    (CTRL_EMITTER_SIZESTART_Y, "sizestart_y", 1),
    (CTRL_EMITTER_SIZEEND_Y, "sizeend_y", 1),
    (CTRL_EMITTER_SPREAD, "spread", 1),
    (CTRL_EMITTER_THRESHOLD, "threshold", 1),
    (CTRL_EMITTER_VELOCITY, "velocity", 1),
    (CTRL_EMITTER_XSIZE, "xsize", 1),
    (CTRL_EMITTER_YSIZE, "ysize", 1),
    (CTRL_EMITTER_BLURLENGTH, "blurlength", 1),
    (CTRL_EMITTER_LIGHTNINGDELAY, "lightningdelay", 1),
    (CTRL_EMITTER_LIGHTNINGRADIUS, "lightningradius", 1),
    (CTRL_EMITTER_LIGHTNINGSCALE, "lightningscale", 1),
    (CTRL_EMITTER_LIGHTNINGSUBDIV, "lightningsubdiv", 1),
    (CTRL_EMITTER_LIGHTNINGZIGZAG, "lightningzigzag", 1),
    (CTRL_EMITTER_ALPHAMID, "alphamid", 1),
    (CTRL_EMITTER_PERCENTSTART, "percentstart", 1),
    (CTRL_EMITTER_PERCENTMID, "percentmid", 1),
    (CTRL_EMITTER_PERCENTEND, "percentend", 1),
    (CTRL_EMITTER_SIZEMID, "sizemid", 1),
    (CTRL_EMITTER_SIZEMID_Y, "sizemid_y", 1),
    (CTRL_EMITTER_RANDOMBIRTHRATE, "randombirthrate", 1),
    (CTRL_EMITTER_TARGETSIZE, "targetsize", 1),
    (CTRL_EMITTER_NUMCONTROLPTS, "numcontrolpts", 1),
    (CTRL_EMITTER_CONTROLPTRADIUS, "controlptradius", 1),
    (CTRL_EMITTER_CONTROLPTDELAY, "controlptdelay", 1),
    (CTRL_EMITTER_TANGENTSPREAD, "tangentspread", 1),
    (CTRL_EMITTER_TANGENTLENGTH, "tangentlength", 1),
    (CTRL_EMITTER_COLORMID, "colormid", 3),
    (CTRL_EMITTER_COLOREND, "colorend", 3),
    (CTRL_EMITTER_COLORSTART, "colorstart", 3),
    (CTRL_EMITTER_DETONATE, "detonate", 1),
]


class ControllerKey:
    def __init__(self, ctrl_type, num_rows, timekeys_start, values_start, num_columns):
        self.ctrl_type = ctrl_type
        self.num_rows = num_rows
        self.timekeys_start = timekeys_start
        self.values_start = values_start
        self.num_columns = num_columns
